language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PLq93blRILZRPHkJBzOTkxXiXT7+emZnmcHo9w+qXsRGk0jx1oTwuIBEqkvKWu1G2Mz80X+R4H6maPK9p32rBHuENnqyASZtw1b1jeSmTECltmXIqjSZJs+rGp3gusBcsvyGXAymvt6RE+iAjCiXquqgtCA0ClKdjrK15NjCGNCuIK4vx5YF1n8hfq2yYET/nJIi9nE9+XR4HNtMsZeQSUXfmH9qqBDwfelonpR7kiPOAamQWBclBy5UBHqdn24zXAk0sHdjSbKnAS0BljxFk/NsFTWcIuOAk0opA2uQdfqa8o8gyeusKPL4CYcBXyL2JDiueWz+pJYNlY6ab17lm3isXM14FXd1l9muWsvtj1LsNmLkVrBkdBlYeChhNc+xHdt+Z9m9l73NjDQasM0qThUjTggHdhQLmqnG3Wyg0HfTKFYD/QV3GrBB+vULxtqigdqyKdbON0+YOLMXHUBbxwbTOCG13D95NHiqZXEobLy1Q54ZvNE9EwFX0ayul+zq9+CtLU/bOlGEXX7lOk1k6xVptCwUeKhNnFkWUFlPHBodIMvGGi/a1iBVOW0PdPGd+ZeeuzZmukaudiDlASAAdZY4C6CWWyR3TQXfYauoeY9fof3mAYBRprW05iUv+TOsicFsqfpclnAaw9FoFU7zNNjRH2CUwterCSMLcBhz7Bg=
  app: aqueous-badlands-89875
  on:
    repo: thinkful-cohort-16/mongoose-blog-app-testing
